### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EggFriedCheese** [lilserf/bot-on-the-clocktower#165] opened 2023-06-23 09:26 UTC
Bot on the Clocktower encountered an error.

Please consider reporting the error at <https://github.com/lilserf/bot-on-the-clocktower/issues> and including all the information below:

Interaction error [Guild: `840323781066489946`
Channel: `1105909768478007398`]
Exception: `TimeoutException`
Message:   `A timeout occurred after 30000ms selecting a server using CompositeServerSelector{ Selectors = ReadPreferenceServerSelector{ ReadPreference = { Mode : Primary } }, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 }, OperationsCountServerSelector }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "ReplicaSet", Type : "ReplicaSet", State : "Connected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/cluster0-shard-00-00.eylae.mongodb.net:27017" }", EndPoint: "Unspecified/cluster0-shard-00-00.eylae.mongodb.net:27017", ReasonChanged: "Heartbeat", State: "Connected", ServerVersion: , TopologyVersion: { "processId" : ObjectId("649318caac5146882b267da7"), "counter" : NumberLong(5) }, Type: "ReplicaSetSecondary", Tags: "{ nodeType : ELECTABLE, provider : AWS, workloadType : OPERATIONAL, region : US_EAST_1 }", WireVersionRange: "[0, 17]", LastHeartbeatTimestamp: "2023-06-23T09:22:42.3959997Z", LastUpdateTimestamp: "2023-06-23T09:22:42.3960005Z" }, { ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/cluster0-shard-00-01.eylae.mongodb.net:27017" }", EndPoint: "Unspecified/cluster0-shard-00-01.eylae.mongodb.net:27017", ReasonChanged: "ReportedPrimaryIsStale", State: "Disconnected", ServerVersion: , TopologyVersion: , Type: "Unknown", LastHeartbeatTimestamp: null, LastUpdateTimestamp: "2023-06-23T09:22:33.3634972Z" }, { ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/cluster0-shard-00-02.eylae.mongodb.net:27017" }", EndPoint: "Unspecified/cluster0-shard-00-02.eylae.mongodb.net:27017", ReasonChanged: "Heartbeat", State: "Connected", ServerVersion: , TopologyVersion: { "processId" : ObjectId("6493d8fb251af2de6c6eb0b3")

**Comment by magroader** [comment] 2023-06-26 03:00
Thanks for reporting! This is a duplicate of #164 so I'm going to close it so we have just 1 issue.

**Closed by magroader** 2023-06-26 03:00 UTC
